name: "CI"

on:
  pull_request:
    branches:
      - "*"
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - "main"
      - "master"

jobs:
  lint-ansible:
    name: AnsibleLint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6.0.2
